# Generated by Django 3.0.1 on 2019-12-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('LandID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('CurrentSoilMoisturelvl', models.PositiveSmallIntegerField()),
                ('CurrentLightIntensitylvl', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('PlantID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('plantName', models.CharField(max_length=20)),
                ('OptimalSoilMoisture', models.PositiveSmallIntegerField()),
                ('OptimalLightIntensity', models.PositiveSmallIntegerField()),
                ('LandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Land')),
            ],
        ),
    ]
